Repository OceanBioME/OceanBioME.jl, pull requests merged in 2023-07, with the labels that each got.

#120 Generalize `TwoBandPhotosyntheticallyActiveRadiation` kernel to allow curvilinear grids
  src/Boundaries/Sediments/Sediments.jl
  src/Boundaries/Sediments/simple_multi_G.jl
  src/Light/2band.jl
  src/Light/Light.jl
  src/Models/Individuals/SLatissima.jl
  src/Particles/tracer_tendencies.jl
  test/test_light.jl
Labels: bug

#123 Remove DiffEqBase from dependencies
  Manifest.toml
  Project.toml
Labels: package

#124 Minor examples cleanup + add missing dep for box_npzd example
  examples/box.jl
  examples/box_npzd.jl
  examples/eady.jl
Labels: documentation

#122 Update Oceananigans dependency + run CI and Docs on julia v1.9
  .github/workflows/documentation.yml
  .github/workflows/tests.yml
  Manifest.toml
  Project.toml
  README.md
  docs/Project.toml
  docs/src/index.md
  src/OceanBioME.jl
  test/test_LOBSTER.jl
  test/test_NPZD.jl
  test/test_sediments.jl
Labels: package

#121 Sediment model fixes + simpler model
  Project.toml
  docs/make.jl
  docs/oceanbiome.bib
  docs/src/model_components/sediment.md
  src/Boundaries/Sediments/Sediments.jl
  src/Boundaries/Sediments/coupled_timesteppers.jl
  src/Boundaries/Sediments/instant_remineralization.jl
  src/Boundaries/Sediments/simple_multi_G.jl
  src/Models/AdvectedPopulations/LOBSTER/LOBSTER.jl
  src/Models/AdvectedPopulations/NPZD.jl
  src/Models/Individuals/SLatissima.jl
  src/Models/Models.jl
  src/Particles/Particles.jl
  test/runtests.jl
  test/test_LOBSTER.jl
  test/test_NPZD.jl
  test/test_light.jl
  test/test_sediments.jl
  test/test_slatissima.jl
  test/test_utils.jl
  validation/LOBSTER/steady_state.jl
Labels: bug, enhancement, science

#125 Better References in Docs
  README.md
  docs/Project.toml
  docs/make.jl
  docs/oceanbiome.bib
  docs/src/assets/citations.css
  docs/src/index.md
  docs/src/model_components/air-sea-gas.md
  docs/src/model_components/biogeochemical/LOBSTER.md
  docs/src/model_components/biogeochemical/NPZ.md
  docs/src/model_components/biogeochemical/PISCES.md
  docs/src/model_components/individuals/slatissima.md
  docs/src/model_components/light.md
  docs/src/model_components/sediment.md
  examples/column.jl
  examples/eady.jl
  src/Boundaries/Boundaries.jl
  src/Boundaries/Sediments/instant_remineralization.jl
  src/Boundaries/Sediments/simple_multi_G.jl
  src/Boundaries/gasexchange.jl
  src/Light/Light.jl
  src/Light/morel.jl
  src/Models/AdvectedPopulations/LOBSTER/LOBSTER.jl
  src/Models/AdvectedPopulations/NPZD.jl
  src/Models/Individuals/SLatissima.jl
Labels: documentation
