Repository OceanBioME/OceanBioME.jl, pull requests merged in 2023-11, with the labels that each got.

#156 Fixed some `show` methods
  Project.toml
  docs/make.jl
  docs/src/model_components/biogeochemical/LOBSTER.md
  src/Light/2band.jl
  src/Models/AdvectedPopulations/LOBSTER/LOBSTER.jl
  src/Models/AdvectedPopulations/NPZD.jl
  src/OceanBioME.jl
  src/Utils/negative_tracers.jl
Labels: enhancement, package

#157 Bump Oceananigans to 0.90
  Manifest.toml
  Project.toml
  README.md
  docs/Project.toml
  docs/src/index.md
  docs/src/model_components/individuals/index.md
  docs/src/model_implementation.md
  docs/src/quick_start.md
  src/Light/2band.jl
  src/Light/Light.jl
  src/Models/AdvectedPopulations/LOBSTER/LOBSTER.jl
  src/Models/AdvectedPopulations/NPZD.jl
Labels: package

#155 (0.9.0) Fix typos in code, docs, and docstrings
  Project.toml
  README.md
  docs/src/index.md
  docs/src/model_components/biogeochemical/LOBSTER.md
  docs/src/model_components/individuals/slatissima.md
  docs/src/model_components/sediments/instant_remineralisation.md
  docs/src/model_implementation.md
  src/Boundaries/Sediments/instant_remineralization.jl
  src/Boundaries/Sediments/simple_multi_G.jl
  src/Models/AdvectedPopulations/LOBSTER/LOBSTER.jl
  src/Models/AdvectedPopulations/LOBSTER/carbonate_chemistry.jl
  src/Models/AdvectedPopulations/LOBSTER/core.jl
  src/Models/AdvectedPopulations/LOBSTER/fallbacks.jl
  src/Models/AdvectedPopulations/LOBSTER/oxygen_chemistry.jl
  src/Models/AdvectedPopulations/NPZD.jl
  src/Models/Individuals/SLatissima.jl
  src/OceanBioME.jl
  src/Utils/makie_recipies.jl
Labels: documentation, package

#159 (0.9.1) Move testing and docs to buildkite (+ minor GPU bug fix)
  .buildkite/pipeline.yml
  .github/workflows/documentation.yml
  .github/workflows/tests.yml
  Project.toml
  README.md
  src/Light/2band.jl
Labels: GPU, tests
