Repository OceanBioME/OceanBioME.jl, pull requests merged in 2023-10, with the labels that each got.

#76 JOSS paper
  CITATION.cff
  README.md
  docs/Project.toml
  paper/column_example.png
  paper/eady_example.png
  paper/figures/Manifest.toml
  paper/figures/Project.toml
  paper/figures/column-fig.jl
  paper/figures/column.jl
  paper/figures/eady.jl
  paper/figures/eady_plot.jl
  paper/paper.bib
  paper/paper.md
  paper/phytoplankton.png
Labels: joss

#148 Add citation info in `README` + Docs
  README.md
  docs/src/index.md
Labels: documentation

#146 Update Documenter + some polishing
  Manifest.toml
  Project.toml
  docs/Project.toml
  docs/make.jl
  docs/oceanbiome.bib
  docs/src/contributing.md
  docs/src/model_components/biogeochemical/LOBSTER.md
  docs/src/model_components/biogeochemical/PISCES.md
  docs/src/model_components/biogeochemical/index.md
  docs/src/model_components/individuals/index.md
  docs/src/model_components/individuals/slatissima.md
  docs/src/model_components/sediments/simple_multi_g.md
  docs/src/model_implementation.md
  examples/box.jl
  examples/box_npzd.jl
  examples/column.jl
  examples/data_forced.jl
  examples/eady.jl
  examples/kelp.jl
Labels: package
