Repository OceanBioME/OceanBioME.jl, pull requests merged in 2023-06, with the labels that each got.

#106 Add `Docs/Visualization` page + convert figs to vector form (`svg`)
  .gitignore
  README.md
  docs/Project.toml
  docs/make.jl
  docs/oceanbiome.bib
  docs/src/index.md
  docs/src/quick_start.md
  docs/src/visualization.md
  examples/NPZD.jl
  examples/box.jl
  examples/box_npzd.jl
  examples/column.jl
  examples/data_forced.jl
  examples/eady.jl
  examples/kelp.jl
Labels: documentation

#109 small GPU bugfix
  examples/kelp.jl
  src/Boundaries/Boundaries.jl
  src/Boundaries/Sediments/Sediments.jl
  src/Boundaries/Sediments/simple_multi_G.jl
  src/Boundaries/gasexchange.jl
  src/Light/2band.jl
  src/Light/Light.jl
  src/Models/AdvectedPopulations/LOBSTER/LOBSTER.jl
  src/Models/AdvectedPopulations/NPZD.jl
  src/Models/Individuals/SLatissima.jl
  src/Utils/negative_tracers.jl
  src/Utils/sinking_velocity_fields.jl
Labels: GPU

#112 Add GPU info in README
  README.md
Labels: documentation, GPU

#110 Update Oceananigans/KernelAbstractions versions
  Manifest.toml
  Project.toml
  docs/Project.toml
  docs/display_parameters.jl
  docs/src/model_components/individuals/index.md
  examples/NPZD.jl
  examples/PlottingUtilities.jl
  examples/column.jl
  examples/convergence.jl
  src/Boundaries/Sediments/Sediments.jl
  src/Boundaries/Sediments/coupled_timesteppers.jl
  src/Light/2band.jl
  src/Light/morel.jl
  src/Models/AdvectedPopulations/LOBSTER/LOBSTER.jl
  src/Models/AdvectedPopulations/NPZD.jl
  src/Models/Individuals/SLatissima.jl
  src/Particles/Particles.jl
  src/Particles/tracer_tendencies.jl
  src/Utils/negative_tracers.jl
  src/Utils/timestep.jl
  test/runtests.jl
  test/test_utils.jl
  validation/LOBSTER/steady_state.jl
Labels: GPU, package

#113 added advection back to examples
  examples/column.jl
  examples/data_forced.jl
  examples/kelp.jl
Labels: documentation

#114 Minor docs cleanup
  Project.toml
  README.md
  docs/make.jl
  docs/oceanbiome.bib
  docs/src/appendix/library.md
  docs/src/appendix/params/index.md
  docs/src/gallery.md
  docs/src/index.md
  docs/src/model_components/biogeochemical/index.md
  docs/src/model_components/sediment.md
  examples/column.jl
  examples/data_forced.jl
  examples/eady.jl
  src/Boundaries/Boundaries.jl
  src/Boundaries/Sediments/Sediments.jl
  src/Boundaries/Sediments/coupled_timesteppers.jl
  src/Boundaries/Sediments/simple_multi_G.jl
  src/Boundaries/gasexchange.jl
  src/BoxModel/boxmodel.jl
  src/BoxModel/timesteppers.jl
  src/Light/2band.jl
  src/Light/Light.jl
  src/Light/morel.jl
  src/Models/AdvectedPopulations/LOBSTER/LOBSTER.jl
  src/Models/AdvectedPopulations/LOBSTER/carbonate_chemistry.jl
  src/Models/AdvectedPopulations/LOBSTER/core.jl
  src/Models/AdvectedPopulations/LOBSTER/oxygen_chemistry.jl
  src/Models/AdvectedPopulations/LOBSTER/variable_redfield.jl
  src/Models/AdvectedPopulations/NPZD.jl
  src/Models/Individuals/SLatissima.jl
  src/OceanBioME.jl
  src/Particles/Particles.jl
  src/Particles/tracer_tendencies.jl
  src/Utils/Budget.jl
  src/Utils/makie_recipies.jl
  src/Utils/negative_tracers.jl
  src/Utils/sinking_velocity_fields.jl
  test/test_sediments.jl
Labels: documentation

#115 Add `NutrientPhytoplanktonZooplanktonDetritus`, `BoxModel`, and `GasExchange` in Docs/Library
  docs/oceanbiome.bib
  docs/src/model_components/biogeochemical/NPZ.md
  src/Boundaries/gasexchange.jl
  src/BoxModel/boxmodel.jl
  src/Light/2band.jl
  src/Models/AdvectedPopulations/LOBSTER/LOBSTER.jl
  src/Models/AdvectedPopulations/NPZD.jl
  src/Models/Individuals/SLatissima.jl
  src/Utils/negative_tracers.jl
  validation/LOBSTER/sediment.jl
Labels: documentation
